if_cuda: 1
batch_size: 2
if_continued: 0
lr: 0.01
alpha: 1.5
beta: 1
epoch: 50
chk_pth: "./checkpoints"
chk_pth_infer: "./checkpoints/"

range_x:
    - 0
    - 70.4
 
range_y:
    - -40
    - 40

range_z:
    - -3
    - 1

vox_d: 0.4
vox_w: 0.2
vox_h: 0.2

anchors_per_vox: 2
nms_threshold: 0.1
score_threshold: 0.96
iou_pos_threshold: 0.6
iou_neg_threshold: 0.45
pt_thres_per_vox: 35

classes:
    - "Car"
    - "Van"
    #- "Cyclist"
    #- "Pedestrian"
